comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
error_on_line_overflow = true
error_on_unformatted = true
style_edition = "2024"