comment_width = 180
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
error_on_line_overflow = true
error_on_unformatted = true
group_imports = "One"
use_field_init_shorthand = true
use_small_heuristics = "Max"
